// Auto generated by rvos_compiler

#ifndef COMPILED_MODEL_EXECUTE_HPP_
#define COMPILED_MODEL_EXECUTE_HPP_
#include "include/core/tensor.hpp"
namespace rvos {
RamTensor::sptr yolov3_model_execute(RamTensor::sptr input_yolov3_0);
}
#endif // COMPILED_MODEL_EXECUTE_HPP_
